<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCn0Xnty\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCn0Xnty/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCn0Xnty.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCn0Xnty\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCn0Xnty\App_KernelDevDebugContainer([
    'container.build_hash' => 'Cn0Xnty',
    'container.build_id' => 'da20ee5c',
    'container.build_time' => 1649446428,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCn0Xnty');
