<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTbyKAsh\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTbyKAsh/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTbyKAsh.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTbyKAsh\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTbyKAsh\App_KernelDevDebugContainer([
    'container.build_hash' => 'TbyKAsh',
    'container.build_id' => '62d2e469',
    'container.build_time' => 1649564125,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTbyKAsh');
